<a href="https://colab.research.google.com/github/PRAN20/Artificial-Neural-Networking/blob/main/Artifical_Neural_Networking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Artifical Neural Networking**

# **Importing Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

# **Importing DataSet**

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [10]:
x = dataset.iloc[ :,3 :-1].values
y = dataset.iloc[ :, -1].values

In [11]:
x.shape

(10000, 10)

In [12]:
y.shape

(10000,)

In [13]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [14]:
print(y)

[1 0 1 ... 1 1 0]


# **Encoding Categorial Data**

**Label Encode to Gender Colum**

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:,2])

In [16]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


**Hot Encode Geographical Column**

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [18]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# **Splitting Data into Training Set and Test Set**

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# **Feature Scaling**

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# **Building the ANN**

**Initialising the ANN**

In [26]:
ann = tf.keras.models.Sequential()

**Adding the Input Layer and First Hidden Layer**

In [27]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the Second Hidden Layer**

In [28]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding The Output Layer**

In [29]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [32]:
ann.layers

# **Training the ANN**

**Compile the ANN**

In [33]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Training the Model on the Training Set**

In [34]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6080 - accuracy: 0.6886
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4844 - accuracy: 0.7950
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4516 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4333 - accuracy: 0.8016
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4215 - accuracy: 0.8086
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4085 - accuracy: 0.8201
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3935 - accuracy: 0.8347
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3796 - accuracy: 0.8438
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3683 - accuracy: 0.8500
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3591 - accura

# **Prediction And Evaluation**

In [38]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


# **Predicting Test Results**

In [42]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


**Making the Confusion Matrix**

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 199  206]]


0.86

In [44]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1595
           1       0.72      0.51      0.60       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000

